service: mySpotifyData

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  stage: dev
  architecture:
  timeout: 30
  memorySize: 1024
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: gcpSpotifyRunner.json

functions:
  spotifyTrackData_etl:
    handler: spotify/getSpotifyTrackData.trackData_handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: /fetchTrackData
          method: get
          cors: true
          authorizer: null

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 2
  serverless-offline:
    noTimeout: true
  pythonRequirements:
    useDownloadCache: false
    layer: true
    slim: true
    usePoetry: false
    dockerizePip: true

package:
  patterns:
    - "!__pycache__/**"
    - "!.vscode/**"
    - "!node_modules/**"
    - "!countriesLocations/__pycache__/**"
    - "!venv/**"
    - "!.env"
    - "!.envrc"
    - "!.gitignore"
    - "!package-lock.json"
    - "!package.json"
    - "!requirements.txt"
    - "!.trunk/**"
    - "!.git/**"
    - "!.gitignore"
    - "!.gitmodules"
    - "!__pycache__/**"
    - "!.pytest_cache/**"
    - "!.venv/**"
    - "!venv/**"
    - "!node_modules/**"
    - "!/node_modules/**"
    - "!.node_modules/**"
    - "!.serverless/**"
    - "!serverless/**"
    - "!.serverless"
    - "!.serverless_plugins/**"
    - "!.DS_Store"
    - "!.env"
    - "!.requirements/**"
    - "!.requirements.zip"
    - "!.requirements/**"
    - "!aws/**"
    - "!/aws/**"
    - "!aws.env"
    - "!convertorScripts/**"
    - "!tst.json"
    - "!bigqueryQueries/**"
    - "!.mypy_cache/**"
    - "!**/*.csv"
    - "!.vscode/**"
    - "!readme.MD"
    - "!spotifyAuthorizationCode/**"
    - "!accessTokenCurl.txt"
    - "!dropTable.bqsql"
